GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG = 470
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo = "fiqVUyKYYWlkJAqNXOSrNhRIjigSpDgZZdqutbCZNKKNdzTSfOKvOVqMaCwECvDCRBBisHlQfzleiot"
t180 = "moXaWPxOnATsDDzwZbNgYWHTbcbdLEKYuFVZSjDYpwmWnXBfPNvxpJkxDDCpcLJPsPdQnvgtDnAZBIZ"
s178 = 351
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM = "uxmpqFgbVrFoGvOWNAzpBvzuSPxIEcjQEwaoLVsLgFODASjNnaFYSdgaEXPzOZACaWpsjorLbHOUzLX"
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = "pDsaRCyXSgvWLSDTWhTnlNPSJBGovJNJQeNZdmtWxYzyzClCmeKMREWBOdKrdTQQLKtZJhAvfVOAzPy"
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq = 662
X170 = 258
P16874994896354606168 = "MJGvfLrTKfymmSqiKumLwsGsFgwcABEJQmfBZltwMjVTmJZNbtvHmkjqJQRUpESXkgwrooedxbTvoSp"
isRFvwXHwBZLXvuqrNpynMEdANONhKkjFQMYgxXzAZhPeMyPyaXjoDRydAgscxrVHWBBpAzUqVPDOEA166 = "vRARJUUrJVbOXtjMYcMuOwJXsBmXYXjLIEmqbnyFWGwYKgMdGlAOZATtushCowxyRfMCisSwEHWhvgm"
lIlIIIIllllllIlIllIlllllIlIlIllIIIlIlIIIIIIIIllIlllIIlIIIIllIllIlIlIIIllIIlIIlIlIlllIIllIlIlIlIlIIIlIlIIIIllllIIlllIlIlIIIIIIIllIlllIlllllllllllIllIlllIllIlIIllIIll = "NxqXWbNBflUtxVnmtjbTLcqvlOUgmrSUylIvctppZmbnmZFOOxbPlbfMEvOJiOVXUGgaDFdsdXDBbeo"
IIlIIllllIIIIIlIIlIlIIIlllIIllIlllllIIIIlIlIlIlIlIllIIlIIIIlIIIIllllIIIIIIlllIIlIlIlIlIlIIlIllllIllIIlIIlIlIllIlIllIlIlIlllIIIIIIlIlllllllIlIIIIlIlIIIlllIIIIlIlII = "QfEHWzMCGcijuzoMvLEHaRqkVAPJRksYmLaOtFLHktkjNyoutlGWHiwNBYVLFwsSuACKSAFnwPIBtrd"
b16874994896338172160 = 627
l158 = "YbyGhobLAwBGIjhGwgZXltNBekeATYeMsATGxQdbTluuCAuvTdgVnLVleTzaqNajFXTtbUclykeKVlq"
AAaaAaaaAAAAAAAaAAAaaAAAAAAaAAaaaAaAaaAAaaaaaAaaaAAaAaAAaAaaAAaAaaaAAaaaaaAaaAaaaAAaaaaaAaaaaAaAaaAAaAaAaaAAAaAAaAaaAaAaAaaAaAAaAAaAAaaAAAaAaaAaAAaAaaAAAaAa = 831
AaAAaaaaaaaaaAAAaAaaaaaaaaaaAAAaaAAAaaaaaAaAAaAAaaaAAaaaAaAaaAAaAAaAAAAaaAAaaAaaaaaaAAAaaaAAAaAaAAAAaAAAAAaAaaaAAAAAAaaaaAAAaAAaaAAaaAAAAaAAAAAAaaAAaaaAAA = 904
O152 = "lZPIakmJHwKziWrwnaquaqlcfVvyFWmlYliyjBzFbJZqJrjfmpsjLgCTpjADkQvrQFPNpefiuEvSzFU"
V16874994896324883150 = "yDsGHAiETOccERObmXdCKSXKaSagBZJYTknViBGurhjccXWvdkHcPwiFaaILoNvioazTLFSITOyyled"
D16874994896322584148 = "wyVSMRTykdCPmBLtTTmuLIptvwKJuDAHEvvQnOakqPxoQKRncFWlnAUyvofooAurZgbLhOqWHheeitV"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = 400
q1687499489631998144 = "rGKjsixNfTgNELXiLFifbtLRZzQfEFHsNutxbVgWAsgNLEzRLyWsiOaUXGdPlxYrGDoZXZAJRijziFV"
C142 = 327
s140 = 143
LQWnapIEAITSvkthpBpMSKjYafgEzMlMzxIglDFoOPREUOQUvHYoDzFEAOORWceozpMbmgtlRbsTeUp138 = "XBAYRQWGrFnqmrYCuwpxtyEORDYRiAXbLxvwPxQLqkYRXRrqSxQfMdIWGgxMoGYfBjpnWInMJaPBRvs"
U136 = "WbkVtHWUXcOWBjpgiRJLwTucZjhbwLoWFEauUZHigXJvFGgzsVxZiNUbqBPoFtwrMpeDiERsPAllbTv"
IlIIlIlllllllllIIIIlIIlIlIIlIIIIllllIIIlllIIlIIIlIIIllIlllIlIllllllIIIIllIIlllIIIllIIIllllllllIIIIIIIllIIIIlIIlIIllIlIlIlIlIllIIIIIIlI = "nUfOWxCaALiSntKVFPBZwAMKpQceJPDawmvZPtdEyDTBYOlDZVPTLArgqvSaiuTcAXtKDeBbcWvKHLi"
aaaaAaaaAaaAAaaAaAAAaaAaAaAaAaAaAaaAAAaAaAAAaAaAaaaaaAaaAAaAaaAaAAaAAaAaAAAaAaAAaaAaaaaaAaAAAAAAaaaaaAaAaAAaAAaAAaaaAAaAaAaaAaaaAaAa = "NkhFoqMyptcAuBSwwbrCHbIxWXhMiKTXdKYjLXBXBOuDhEaqoTsYxuxwWZikGGdHWHjouYjarmtvzFJ"
IIlIIIIIlIlIlIIlIllIllIIlIlIIllIlllllIIlIIlllIIIlllIlIIIIIIllIllllIlIllllllllIIIIIIIIIIllllllIIIlIIIlllllIllIlllIIlIlIllIlIlIllIlI = 549
aaaaaAaaaaaAaaAAAaAaAAAAaaaAaaaaaAaaAaaaAAaaaAaaaAAAAAaAAAaaAAaAaAaaaaaaAAAAAAaaAaaAaaAaaaAAaAaAAaAaAaAAaaaAAaAaaAAaaaAAaaAAAaaa = 456
llIIlIlIllIlllIIIIllIIIlIlIIllIlIlllIIllIIIIIIIlllIIlllIIIIIllllllIIlIIIIIIIIlIllIlIlIllllllIIllllIlIlllllllIIllIlIIlIlIlIlIII = "RySGfvyZavqjczrYhZNqizTZzUCgrlRMVhhQqmcbHABFdJZGVZlBaeIUvOAxnCHxAeVLVmhlXnoXwNt"
B16874994896292002124 = 265
p16874994896288946122 = 260
R120 = 303
k118 = 854
CeDNdCsRTnJazrGaaAXKkDtylCKozEHbuGPiXRbfyFTORmZlxVwrllTJqWEGuushuKlbghfTPbXoCre116 = 319
o114 = 333
LsdSbYppnXRSHNuycqWWxXDkIegeKdkJjgKtHayefcMRmMnavrnjgmwfHZidNgLcDNLYQondBtoirCn112 = "QmDXnUiBIIajCqqZiLIyrcuYaArzpHocenXsIalecHBtjIFaDUUnIaGwKVBQRjyYmuJPIhqLqpCjOYf"
S110 = "gbrOGQZqwjzVRJICbTvZKdffhvtXlXHeKCdrlTRIDZZnxpTMMIWFYNeBupQlusGRqiGbYQZEHmsNLSW"
IIlIlIlllIIIllIlIIllIIlIlllllIllIllIlllIlIIIIIllIIIIllIIIIIIlIlIllIIIlllIlIIIlIlIlllIIIlIlIIIllIIlIIllIIllII = "SDGIhAeRSddSQhrpENDSgPCudXgwLqXtTrZgjLBSxuFKFItJAGEunEdBgdXmtXuzpNSIlImWPPHaEiS"
AAaaAAAaaaaaaaAAAAaaAaaAAAAAAaAAAAaAaaAAaaAaAaaAAaAaAaAAAaaAAAaAaaaAAAAAAAaaaAaaaAAaAaAAaAAaaAaAaAaAAaAAAa = "chvheApqWsywDJRIozfjPdEiwAlriyLUZIjqgvSHvhmuLJWmybKmrnUOuxYKAbZKPVJUKtSucRCourb"
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = "AawiVwKPUgOHwGWuZwdRCFudFBVmxtrABrqbuXhzzcgymxkdbSkBwFfBTyUQnaMvQuxzmwEZLGxedxH"
AAaAaAaaAAaaAaaaAaAaAAAAAaAAAAaAaaaaaAAAaaAaaaaaAAaaAaAAAaAaAaAAAAAaaaAAaAAaaAaAAaaaAAAaaaAAaaaAAaaaAA = 375
CHUruiiaNjvLLGWJlWSgRaxAurgBsjkBNBRkCyRLFmDQctsNBtcKioUAoDqZjTSxAtUSOJkuNFgxGBh100 = "KQVUoaimKagyffMarkNFYRkJfLyfdFJLJeHMAzkbRGCJmrKWkNBHqBqFiZozwzZdbpyFPfjahYKNSUw"
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = "RTirfXrkETAmHrormqftwoTTaHfMmUeHcLtpBELJWQKwxahwhSjDQruVCpHydbPCvDaEnHIcwZJXLNO"
pssTAkkRhHhiHPfbCnnKNCEonMElTgWNPfewUpQJJgBEoCPDJLMgzFrOIqGuzLRqWUBIWzfBoqkcLTz96 = 869
r94 = 684
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = 339
L1687499489624559690 = 370
r1687499489624302488 = "nnKhUxylKepkEzmQdesNXLzqiLxXxQXiYOjzMQOzhSfMXztqhInfxHZleULgfuwBuPWHpYVGKlnkJxn"
E86 = 489
IIlllIllIllIllIIlllIIIlIIlllIIllIlIIIIIlllIllIIIIlIIIllllllIlIIIIIlllIIIIlIlIlIIllIl = 346
QbOepScTIUbrvYXZQsGDoBLFBBOKlJhLVuvQSwgxPAwZkiEKKPoklijnKkHKZXZOTQfFhlLgwOwbTeE82 = "AgcVcKobURlxmFDvVRAIaCSHROSeQwWEHyjXKpbpBlqahbiHCbiBKjItkuzlClmeUnsXFaRdbmpSnTf"
w80 = 475
u1687499489623087278 = "byXklqUPgWIbQIPVfuZOulWyOFYzMXFYbHitsGbJyzxiEcxMYTzXZqtxQuUqNijlwbOEbDoYZtmmKBl"
AaAaaaAaAaaaAAAAaAAAaaAaaAAaAaAaAaaAaaaAAAaaAaAaaaaAaaAaAaAaAaAAAAAAaAaaaAaA = "NNRtwolrZZbcAHToCcJWalwudPQlZZKfKxhZDerYBMBeQHsDaVqlVYccmvdhFVLGLXOpbLACIvJmwVH"
AaaaaaAaaaaaAaaaAAaAAaAaAaaAAaAAAaaaAaAaaAaAaaAaAAAAAaAaAAAAaaaAAAaAaaaaaa = 511
aaaaaaaAAaaAAAaAAAaAaaaaaAaAaAAaAAAAaaAaaaAaaaaAAAAaaaAaAAaAAAaaAAaAaaaA = 288
s70 = "ndrLqqGuMacDaUjjClhQDBnxXxWpZIgMxapfyVZzepiYMpjknrpAYvAozGoYCWHwENihWsOkTwMMOOm"
D68 = "LvLudbDAhTBBaHEWBSIoPOCFdufCPVCLJVZjIcpLDSACwMAdmmbzPOIIPGNAJzSWuMHNkDBksrmLZJJ"
XvPPynqnMjsvdatPkOacOyPxKBCTTtugajzetGdXBzXVudJNWUvKHkYDsMkrDbeimZVMyfPDoEKOSJK66 = 364
lIIIIIlIIllIIIIllllIllIIlllIIIIIlIllllIIIIllIlIIIllllIlllIlIIlIl = "UdakzFJpwaifQakRYfXGhmcYjoNbuaGeZsOGRptSBXgqbVBzzNHUpeWdOZRQbZXdDBaMHiHiEflCPzg"
aaaaAAaaAAAaaaaaAAaaaaaAaAAAAaAAaAaaaAaaaaAaAaaaaaAaaAAAaAAaAA = "GAnhdlvLoxRDijLBWZBWQSfoXaKxkojLcXMQlMYsLpBsdWKVzLpJfOxnDXERXsZcDClDoVdHctnGNtQ"
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = "DmBGeHmkMFEGmBwfUJDQkarlFhuGtkHsXwgADVWwRNmQUsPQOAJkTtQxYLCgBUlgSOdiEXtcqaQhzmq"
aAaaAaAaAAAAAAaaAaaAaaaAAAaAAaaAaAAaAaAAAaaaaaaAAaAaaAaaaA = 396
aAaaAAAaaaaaAaaaAAaAaaAAAaAaAAaaaaAaaAaAAAaAAaAAAAaaaaAA = 255
AaAAaAAaAaaAAAAaaaaaaaaAAAAAaAAAAaAAAAaAAAaaaaAAaaAaaA = "vMWzMyhhdyCvyDjIDZisFEUOyMuNKENUulyivyzcjulsHTrZMLjUiqZKBxxRSwUZKOdTVBCDdpdcQXn"
AAAAaAAaaaaAaaaaAaAAaAaaAaAAaaaaaAAaaaAAaaaAAaaaAAaa = 282
TnOaNlgdAeyEjGcHTmUlOJFCrIwFuCeHJrQeoaMdCsWNjxixNjLrXvZupYgfgIEgJaKXOHqzwQiMurK50 = "wdcdBHRfeetVVvfGgVQQUUMhdPQVVUAZgtdJZldSEBJdyJyseCuJvgXslzvjGKTfKKNUEanEvcwlfvc"
AaaaaAaAaAAaAaaAAaaaaAAaAaaaaaAaaAaAAaaaaaaaAAaA = "EIzKyHJofcFqvGNRzYFTsYgBEJphLkKUokAfYIqxBDOGFKKktUPUNXALNoscMnTkgeoWvYmUXQCFfEB"
Q46 = 511
SmthOLGrvLRojuXExRrPwHTfZGyIOYoKrgcEELCaplBnPSHYyTNlnasMUspPLQppZvCEwDjAHfVFPuk44 = "DihFmZqNOoeKNuqYjvnCYdvvMimkdjuReFNnjQJZzzsxclKfxbGtOBhQLgbayVmXITSfuFssSopokUJ"
lMIQCgrvUFPHtqglkXFdtBHpdcanuEBoAxMbXvRzPGwBfgvvxlwpZvXKiTbYxhMihMZjFXTLVxKuDub42 = 193
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = "DAudAmMyjmArQYkqpXsPnKKlySeoEASVSQSrGyEEvGAMVoRHsNKRldmeHGqpSDlJREiXHQfMvIOfcQy"
AAaaAaaAAAAaaAAAaAaAaAAAAAAaaaaaAaaAaa = 866
KoMVSIvQDXYFuGpfMyvfEssqdIOXDlFOJQkSHmEzRqCLdGdVDcFcFqFRaUUGMPsUzWbYXcmRosafCtW36 = "ArtPhkhIxTWxOwVgEwNFAZMRjmwTbIgSqZlcPzTNsMarLupXOlOrVfZGgGqDHzpnQpbLuwLCtKeQXQA"
aaaaAaaAaaAAaAAaAAaAaaAAaAaAAAAAAA = "tOduVPbkyyCXzsMzxPLIJGridWpDIVCSKgtDNjxljZvqEjgvdYUFGbFmiZopTAeaMcloRFFzGcGzoBo"
AaaaAAaAAaaaAAAAaaAaaaaaAAAAAaAA = 205
wozGDXEjshEqogSucqscwFisLJtsOCqyUEpMqtXnSsGvtSHQHvVLSQbJmqPhYZQhAcvqtmpEdvIWIng30 = "RfHPjUmjivJEiSpOKDISqcWMflDLhgrFguePHPgEeWvbLZndwIVOdwqrQvKLTrKwiBmgZeedViPqUWU"
t1687499489616799828 = "QvzYLICtcYJIAyzphpKUYfERFVBAgoSturPgMPjzUoLYkRHsPydnvyddGMNFVAYhNhFxIpEXpzMYnPx"
fLZZtdbtXOlbgIEDpXWMnjESSnUyLiVcFAAqbMLDTvLwjHuCzQAAITcoBBHoPKuHpeCMXWNzBpyUEvS26 = "rDFdQKucJVumDCgciXTsxTCcXTSzyHKsvslnzSsHWJvCfJmDNKAFcTaBbReaqMPeLTQHSLtbSorWTNP"
CLVQAoWdJchlEkMOgNBLfWrIkudRjaMBJeRmmbzeGFZuKZjvRRpHiFESynrjaScdLSexLBWKiNzNOtu24 = "npaJQfhQZzNNWIkqQAXMxqooFVftuGDnbqXTBHrOeIKdXWtRmyXPldnWYlxUERVMOIRDNdkCdgNbAED"
u1687499489615918422 = 493
AaaaaaaAAaaAaaAAaAaA = "VYhcAwvaFlPXSkwMYbpTVzGONvZJNMboFZyPREpmnRHpfJzOCLunEbfnrwpQwfZRgBBEuLFlHyucxHZ"
llIIlIlIIlIlIIIlll = "vxXgpkKMkRWegDGzeXKjKLQcybJTjvGuUDQAlWYKOyTcDHEOmeQbBLsWiMVZmmoDQflZPEhYQwXYJIm"
G1687499489615285416 = "KXGgTdVJKxXIZRxKwXXIiJYUoSVsSWRaVHKHoDeLvELVmkJMGlNvsbBYVvlJmFWNwwgEKnvZaQXHIbx"
bzJHhgOKSqfJyLZvHeUusozLCWooZXxUAtHYMxOxSxZYtSlgRVJaiVUVznCUSunDrzCGnwBEWYMcMqx14 = 239
IIIIIIIIIIII = "AveftMUXCvZOZtGhbuRLJKaBwTnwslxJunOdkcHAGVLkukuZVxChdrtjBSjARHwpJxqKqjtoiiHMqKn"
B1687499489614507210 = 481
aAAAaaaa = 292
IlIIll = 332
GrolrHHUlxttDpmbmCRvQzGVJVvxxcAdlWLkaYuNZeZvtvxZSPsXuvMlkOCFepDVpwhPIaBPlTukbvh4 = "jYircCUubjQIUuVNmpUzpLsObIuXgXYAJEpLvzkeLfyNyXYOPfZoFqnRHKwljNiBTXRyRpiCjQbiXpv"
ll = "zTfWyzlFznOZUtsJVGPwKBEPpGOyenBGyhHYELwNlssHoWQkUMHbAEItScMurhdKynIJKBTcyySTEMm"

#meta developer: @s1zex
import logging
from .. import loader, utils

AEtmGWInkidumEcbSMptMWoqyyQiqBlTeCKvTwaNhSkFuvdMUtVGbwnfXORGHMYFhWaQOXhdOLqQSYY1 = logging.getLogger(__name__)


@loader.tds
class ShriftMod(loader.Module):
    """шрифт наебашит"""
    WErEBUtoiJhZJeHNLlIRxajqukZYpARLcnOtTgeMqrkyHgyMiYeJZESrtElcpzRvHkDgBwIICQkPubQ2 = {"name": "s1zexSH",
               "nety_teksta": "<b>нету текста для изменения</b>"}

    async def client_ready(self, k168749948960981513, db):
        self.client = k168749948960981513

    @loader.owner
    async def shcmd(self, soobshenie):
        """<любой текст или реплай>"""
            
        UZozAutmPdgaFZtYccRKRRaxaoVBwSTpWGBuWtZVWENvNUfaVMKwwnIBuoutcZiwqiuVJlHsDvQfRTN4 = await soobshenie.get_reply_message()
        AaaaA = utils.get_args_raw(soobshenie)
        if not AaaaA:
            if not UZozAutmPdgaFZtYccRKRRaxaoVBwSTpWGBuWtZVWENvNUfaVMKwwnIBuoutcZiwqiuVJlHsDvQfRTN4 or not UZozAutmPdgaFZtYccRKRRaxaoVBwSTpWGBuWtZVWENvNUfaVMKwwnIBuoutcZiwqiuVJlHsDvQfRTN4.text:
                await utils.answer(soobshenie, self.strings("nety_teksta", soobshenie))
                return
            else:
                D168749948961105136 = UZozAutmPdgaFZtYccRKRRaxaoVBwSTpWGBuWtZVWENvNUfaVMKwwnIBuoutcZiwqiuVJlHsDvQfRTN4.raw_text
        else:
            D168749948961105136 = AaaaA
        aYHOtghZuhTUOMOXFmFGPzgbkUFGbuEhmcqodLwlHsNvaFBCikLUrysuwmXxqFPKHKReQVlIUdxPeMj8 = ""
        for simvol in D168749948961105136:
            if simvol.lower() in lqGVzedHeKgPsqdrMvWOJMTrbsjVrQlhVVAwmBsjJEzFRKcIxLmjJZpZkKxEOJCGJgTJXiMTTDVzeeg12:
                vQeCnlmJrHbOPZQgDeJvXfiHOfQnHVbTOtLGRAULNJhRIkQqMyhBTrVAxdgKGafNMmWjgofMJnAyZsb9 = lqGVzedHeKgPsqdrMvWOJMTrbsjVrQlhVVAwmBsjJEzFRKcIxLmjJZpZkKxEOJCGJgTJXiMTTDVzeeg12[simvol.lower()]
                if simvol.isupper():
                    vQeCnlmJrHbOPZQgDeJvXfiHOfQnHVbTOtLGRAULNJhRIkQqMyhBTrVAxdgKGafNMmWjgofMJnAyZsb9 = vQeCnlmJrHbOPZQgDeJvXfiHOfQnHVbTOtLGRAULNJhRIkQqMyhBTrVAxdgKGafNMmWjgofMJnAyZsb9.upper()
            else:
                vQeCnlmJrHbOPZQgDeJvXfiHOfQnHVbTOtLGRAULNJhRIkQqMyhBTrVAxdgKGafNMmWjgofMJnAyZsb9 = simvol
            aYHOtghZuhTUOMOXFmFGPzgbkUFGbuEhmcqodLwlHsNvaFBCikLUrysuwmXxqFPKHKReQVlIUdxPeMj8 += vQeCnlmJrHbOPZQgDeJvXfiHOfQnHVbTOtLGRAULNJhRIkQqMyhBTrVAxdgKGafNMmWjgofMJnAyZsb9
        await utils.answer(soobshenie, aYHOtghZuhTUOMOXFmFGPzgbkUFGbuEhmcqodLwlHsNvaFBCikLUrysuwmXxqFPKHKReQVlIUdxPeMj8)
lqGVzedHeKgPsqdrMvWOJMTrbsjVrQlhVVAwmBsjJEzFRKcIxLmjJZpZkKxEOJCGJgTJXiMTTDVzeeg12 = {"а": "ⲁ", "б": "ⳝ", "в": "ⲃ", "г": "ⲅ", "д": "ⲇ", "е": "ⲉ", "ё": "ё", "ж": "ⲯ", "з": "ⳅ", "и": "υ", "й": "ύ", "к": "ⲕ", "л": "ⲗ", "м": "ⲙ", "н": "ⲏ", "о": "ⲟ", "п": "ⲡ", "р": "ⲣ", "с": "ⲥ", "т": "ⲧ", "у": "ⲩ", "ф": "ⲫ", "х": "ⲭ", "ц": "ц", "ч": "ⳡ", "ш": "ⲱ", "щ": "ⳃ'", "ъ": '"', "ы": "ы", "ь": "'", "э": "э", "ю": "ю", "я": "я"}
VMTMmsIeaSwPKMeyrpnNgJmScKKxeWUShCgpIGzoQrpznzpapohaqHaTrIZXUaLHPdFfmpSIUgdbBNJ1 = "StMrlWybpgPawnUjEzQorEwVTXCWeoEWTxGGfsvSKBkZqPGGdlhpwehCiTObKyMnVXIFXfwXSbWjpVZ"
o3 = 276
OOOOO = 354
o16874994896144267 = 307
IIIIlIlll = 119
aAaAaAaAaAA = "WsoETodEttkhEohPmbQVjRttsHSnHPIbLhGpFNzOhAvbOipsteEWknIJugNyzOFihYliDCmtCNiIYpx"
OOOOOOOOOOOOO = "QoSVSbAxDuAOsXiNCOUyhGwqpauZTtiUiyAJAuQbNGuzXzyLXuOwvbKwqEGmxufRcPTwcGOmNQHtGRe"
d168749948961515515 = "zfnSarnVKYqNySrhwlRCjipLTTVsBqiyeCVDWOFbQlEnVtzNNmGCqDumNmqPZnjQQBjlNavbBoEVZnV"
o1687499489615306917 = 397
AaaAaAAaaaaAAaAAAAA = "ttRXdRDshqgWDJQWPRSKHTbGTvlaaxVcZeJCfMPiWVuMzTaoZTRZvQyOOpMfTLdgLCMAGfiEpoynjhQ"
IlIIlIlllllIIllIllllI = "CQnkQRYxDfAwpCPLjSKHusqwhZmbAmEbUVNqoBFMHcbanMlHovaikMClLqWJjeLkSudphAdxZgCIdyt"
llIllllIlIIIllIlIllIIII = "vaUQxCItpxNqgeszbOeQTjLrYEzwTsHAMfrmdFedXIMduitCmYvXfOoEZaMjcMAJCnqfYQojmpSwqil"
TTTTTTTTTTTTTTTTTTTTTTTTT = 228
lIIllIIlIlIlIllIlllIIlllIIl = "qqqMvHqUFmOPTyQblaAdkTqtwWYiviuxZhgQpZYeMkUWqVSOmtwkUkBvSjsoBDwfnpodCzXOysLcfyy"
aaAAaaaAaAaAaaaaaAAaaAaAaaAAa = 787
AaaaaAAaAaAaAAAaaAAAAaAAaAAAAAA = 637
asTKZVzUGYaIfFeKwPTQPFOSDSWTqAabMZRIDwFtkmZtOBvLPwfCNJgVujCKYuMgKmTzrzbplozpZGB33 = 672
F35 = "QZIuJCQOdHwaUpHKVnURMbAQgylxhCnQEBPJSUpKAUrWNjETVDhlmHLFMMMCOZupzizARKjZvCBlxBu"
O1687499489617931837 = "PBVpIfTMDywHcBWDMnEarUSZdcoSoCRzLDKiBkAzBXlSVfgKHLGKAyRktTmDfXvJOVglWrDDRNHjSdO"
AAAaAaaaaAaAAAAaaAaaAaAaaAAaaaAAaAaaAaA = 671
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = "WAzISiYpbFSvQyEtpZcirDaJzDYYGzBDvYffKfckOxXWOfiGwoZCLDyhSyaEKVdqJiuJCekTgmcuHnz"
y1687499489618547443 = "yFBooCtMcGYDYmQOiXHbTaHKZtxTzqvmKrXrFVZHYGYNDurFGYJueexjlrccrYrKOdoYSdvevkQAmEp"
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = 331
ONPWCdJRvBNezuSZuYtpCYHgXDmLHsqHkOJIOYoQzQPuLziryGoPDriREYjbxGndpynjRsAvSlfPhUK47 = "fgxnGjsTbmqFqWGIRgQBEJqrvliAsDFciTicaljorNJPDZinKRuJjUmycToWRZOCUXjPaagjUCoAkoX"
AAaAaAAaAAaaaaaaaaaaaAaaAAAaAAAAAaaAaAaaaaaAaAaaA = "XtBURFvMbSlfJfFrWjBvVfHRVqxilRwlCOIrXlYiiqoBMXAEoEznVJApgXyPZItnFtDSnNHOItEafOB"
H51 = "mwfVnjUXQQANWKYnCKDHvxifMuPfjsYkBPohCyTBQwqqjyPpLHmBdNviwosSdpyDQVaiiBKtRKQvPVX"
iVHEnFvZtCFyRyuaIGvgnrBulnyLRxhxmvOTpztxhdcIFqPkBxMgGiNjMgrdQvmzYcDXtkXFNquUVNW53 = 496
oaZpVWYJUvrNhDAvJjKNwKMOxJoaePiFUEesLmYyInXFSibLppAZLGcvCysixUYuYWfZwHXLIPQiJYb55 = 165
lIlIIIIlllIllllIlIlIlIlIIlllIlIlIIIIIlllllIllIIIIIlllllII = 371
h1687499489620523259 = 462
UYhxGhdwyzBjunuJjyOhkaxnIIPRndCDMTjoqZYchImKHJmPiOYqaftCXFxxxuamqNpFZHlyvEmubMS61 = "MOQywWfRlBvhGFpHsEzqiJhIDLHoNzYDDLNZpnXoRXdaYVmHwoITneqNMcgbBEURHhMLYrcHaxWspHO"
lIllllIllIIIIllIlllIllIllIlllIIllIllIIllIIllIIIIlIlllllllIllllI = 367
b168749948962138365 = 498
aaaaaAAaAAaaaaaaaAaAAAaAaAAaAaaAAaAaaAaAaaAAAAaaaAaaAAAAAAAaaaaaAaA = 30
MEvzlFTDrIvVMCIFXxnfcmYfjLbBOHHEWQROxjmrbKcVcOGsewCYmwHqvRlKrlCYHPJuHRDLoiLYyOW69 = "GiDjoXTCOKGHauJDqZCmpJFkOPOKglbMQaJzZQPAxwThzkgMZRYtchhuILNmQTPeoSDpBWMdrFupOMy"
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz = "nkGhpPjndOgcwrGgZMQxqLFPbzMqoMCkQJnQzBufMnYbhbakszKofOwSfeReSglkoleTCiNMIiuQKYQ"
Q73 = "PQrXOualjJijRmgPucAhWmQpsJNKvoVJJAyzRYkHgkUxQDKYpNWmQfCkgjyKpjfdawdyFMVOdDTTxiE"
AAAaaAaAAaAaAaAAaaaAaaAAAAAAAAAAaAaaaaAAAAAAaaaaAAAaaaAAAaaaaaAAaaAAAAaaAAa = 311
aAAAAaaaAaAaaAAaAAAaaAaaAAaAaAAAaaAAAaaaaAaAaaAaaaaAAaAAaAAAaAaAAaAaaAAAaaAAa = 687
E79 = "JJfADPpZURvZzbpgKgdXFhASetimTYIPnpavkOKsgUpdewcbMSQmVIPjIUuunXhXrnFsbDMiOuARtth"
AaaaaaaAaAaAAAAAaaAaAAAaaaAAAAaAAAaaAAaaaaaAAAAaaAaAAaAaaAAAaaAAAAaAaAAAAAAAaAaAA = "LureDOSlttaIefhzVYAElmoRLGuONUDrmRUnqUBQprkvHtOYmYzTXsnvfFdBxqLCnTdGfcjQekhddns"
lllIllIIIIllllllIIIIlIlIlIlIlIIIIIlllllllIllllIIllllIlIIlIlIllIlIIllIIIlIlIIlllIlII = "GTPybFpJfdArWNlXYffIbyZrZStxSaXvHtPrhIiPwYawVBxtvBjkwfpiqqquJdSSpieHFHhHLJAKxzL"
x85 = 300
BsEmigpVEofCQDoplbpaGeGqUoFAWYAcEFgTMDhteuDJyFLLyYVjXsasIZrTsdiqSKNCtASkwlHnjVF87 = 482
aaAaAaaAaaAaaAAAAaAaAAaAAaaAaaaAaAaaaaAAaaaaAAAaAAaAaAAaAaaaaAaAaaaaaaAaaAAaAaAAAaaAAAaAA = "sUApeDSRPIBzEnUeyZmeZZpuBHMcUKKTChSopDtxHzeXXhElpHsUnrFlxbCyKEEsKFkxFVLIHHnjCGY"
lIllllIIlIlIIIlllIIlIllIllIlIlllIlIllIlIlIllIIIlIIIlllllIIlllIlIIlIlIIllllIIllIIIIllllIIlII = "fRFrUjEpDIpunqcyiDDDXywRxCqdxTjsWpDjQRrpHtbtBQKeyUcTobgeVQNadBeDSdsMdZtslXMcmhR"
kGCOMkgxkadTfUaGgKCpoSiVTafKqaQFKXFfpVDAPpPJgytfKJJslnRniWCEamTgBucQxFDSMPjDryK93 = 430
OXfdOlhPexKBkLheNlivxsNpjNauzYxkToxCkMbMXYBvBkqPAEFCfansWILnlJHfETJqRYASnxmrPdx95 = "xvthOqYoCkUTQwtvuPUeorsvjhHXHvffLRuQqdbkpzrLbnbBTbHiFrHBMqofklWdqPkxwRSebcJdpiP"
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = "MQhZnyFilVRfxehkbLPETFinDZamructJsAfoFUUzeEsPhvCQQDmmZlWlgxJOjqYRoGEgawOHYSMbnp"
N1687499489625524899 = 421
KompVyINpMLFWNMjyvVFTrnqvyaqZLtrAKpgAGXnJOZVsksKugqFBvhHfJyMyLcVgXxObvatqiiqQoB101 = "GCBZkldLkGlUSficmAbOIYFSTdnJTbPregfEsnVUISyvzSjLaPGwjXYewLBjafXUTwsYQtwZiocGncg"
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = "fuuXQJuxkeMCerSCOXcuFTWSmAMHaJPWMVReATPVsKEOTCHUNwRBQGrjpaQWDnelCaqhBuWGHNotHkV"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = "fNvJUIpPRxLjyjzfgmYeRDAAEprTayVcoNaSephqLGbcAhSCyfyVlYbihaccyuvqztMpJaQgzCkppcH"
yOSfSQoIsfJGKguoyLetMKxVLTlQHsVlAGOhgxsEhhqFsEjpWTlWGdHlzybcLOEDAIzcymLWQLbQgBa107 = 416
AaAAAaaAAaaAaAaaAAaAAaaaAaAAaAAAAaaAaAaaaaAaAAaAAAAaAAaAAaAAAAAAAaaaAAAAaaaaAAaaaaaaaAAaaAaAaaAaAaAaaAaAAAAaA = "cmakAmKcyDrqGxFcECiDewrLvelHGXlUDQnLNzbxBKwwgaddvHRMcUGqUUwGOlSNwBhMQCvRbXOtAux"
llIlllIlIlIllIlllIIIlIIIllIIllIlIIIllIlIlllIIIllllIIlllIIlllIlIlllIIIIIIllllIIIIIlIllIIIlIIIIllIIIIlIIIIlIIIlII = "NnnPVitSPtCFZVjjaQSqJOUnDobxrkBMwGKAPiFMQtfGRIlwdfcgpPzSRWMfIHkriqcJwSNNSvHPZWD"
F113 = 440
aaAaaAAaaAaaAAaAaAaaAaAaaAaaAaAaaaAaAAaaAaaAAaaAAAaAAAaaaAAAaAaaaaAAaaaAaAaaAaAaAAAaAAAaaaAAaAAAAAAaAaaaAaAaaaaAaAa = "tkURhahtmAraWuUqrHDwZWdfkrqaDyhWERkVzhGzGjxmwtYLnFUfctNCIoAHRieDJFNfWOQtubisTDj"
k16874994896285489117 = "nKHhuhKGHTKpfhQQPSBjYDmjmhUHUbCeIKCSDYjvjirwvrDDkRfZBsmGyTvRDGLLbReFpqWYOdMzEmM"
Z1687499489628692119 = "lxaiQDqbdWzAfNcorNsgFDtEwenfnOJqoSojOicNgixYvDsYGeJtAbPfYscBRuZSkyJhLSCkoDClpuS"
aAaaaaAaAaAAaAAAaAaaAAAAAAAAaaaAAaaaAAAAAaaaaaaaAAaaaAaAAaaaaAaaAAAAaAaaaaaAAaaAAaaAAAaaaAAaaaaAAAAaaAAAaAAAaAAaAaAaaAaAa = 252
AAaAaAaaAAaAaaAaaAaaaaAAaAaaaAaaaAaaaAaAAAaAAaaaaAaAAaAAaAAaaAAAAaAAAaaaaAaaAAaAAAAAAaAAaAaaaAaaAaAaAaAAaaaaAaaAAAAAaaAAaAA = "sbRVRvJdPFCsKmopjhlUUSTMJiGoeYyvzPkcLKgEJqqyGKWtdiHhCNibtPAsitIzWJXgkeyhwocuYHS"
x125 = "zyYGNWOJhFywAPFNkxxHGcWIduUEQpYnlQcDSclVXGmXyDqhHppirFpyhfadDrrPKcBFNIjJYYRaWnD"
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = 368
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = "gXcXaNxUFWIvowTQvMYPmdtUldfzxohvgtnmucBhVwanoWuVhdeVTsTMjSxrQCEwMnkkSOtrQBMAtkV"
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = "bvvUQgjXmTSMFVJHrxnuqZXkABFRejeCUvwsOevSuUPFGdhDBcTTcppcASsXvFZkjYSUMzjXysciaUG"
Z133 = 390
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = 351
IllllIlIlllllIIIlIlIllIIIllIIlllIIlIllIlllIlIIIlIIIIIlIIIIlIlIIllllIIlIlIIIlIlIIIIIIIIlIlllIIIlIlIlIlllIlllIlIllIIIlIIIlIlllIIllllIlllllI = "rKLJDYFxsaiQAKSEqmzgTTtNTuITXAOIWPPKIKchJTAkOXHEdUtLhmHzyKyelyWnriBaIdIZCaomApx"
eySrhdhKGjWpyTCPvZmkuIWyyOmhhwPXmKCqkknIEvfForsJgPTgxtxzmrufcbOnpscMFcoKhwWEpjQ139 = "oXjPLgOWAohUodgsKyZKjmOyDUAHwXYvJrjVaEroRVlTeGjQyyeFSDacAHsLKjQMCohiHkHvejrbcxU"
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = "XapqIVIvtlgxWHkUHWOhiNYhNtMNniwXiaKrokvglpriobmAewMaBzOUtYTSIsVGbqoCpRtypOJpXAI"
t1687499489631883143 = 330
K16874994896320179145 = 210
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = "OWQYEXIsjJpVjDEKeTtaiAIpylFjvINFAXjsWFVjibUgVdouhsEqrxCoKYQLuzdQIwISqqnfwDiSEAV"
S149 = "aZlKuatxZslQXqzkesoKOQaYEYalthpNJFNwzuCvLQRUqyIGVrJFSzkQULrFHlbvYhTtRXVQvONGgSl"
llIlIIllIlIlIllIIIlIIIIlIIIIIIIIIIlllIIllIIIllIIIllllllIllIIIIIlIllllIIIlIIlllIllIIllIIlIIIlIllllIIlIlIlIlllllllllllllIlIIIlllIIlIIllIIIIIlllIlIlIIIIll = 727
IIlIIllIIIIIIIllllllllllIlllIIlllIIllIlIIllllIIIIIIlIllllIIIlIlIIIIlIlIlIlIIlIIlllIlllIIIIlIlIIIIIlIIIlIlIIIlllIlllIIllllIlIIIIllIIlIIlIlllllllIlIIIlIlll = 800
qFOcpTGCGiFlPDauvZDITDiewmllTpcvukHPVQpDaofJYvdllTJCYmWLDkmrkwjYDkDxGnieOlvznBQ155 = 332
AAAAaaAAAaAaaaAaAAAaAAAAaAAAAAaAAaAaAaaAaaAaaaAAaaAAAAaaaaAAAaAAaAAAAaAAAaAaaAaAAAAaAaaAaaaaAAAAAAAAAaaaAAAaaAaaAaaAaaaaAAAAAaaaaaaaAaaAaAaAAAAaaAaAAAaaAaaAA = 948
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = 254
lIIIIlIIllIlIIllllllIIIlIlllllIllIIIIIlIIIIllIllIIIIIIllllIllIIllIlIllIIIIIlIlIlllIlIllllllIIlIIIllllIllIIIIlIlIlIIIlIIlIllIlIlllIlIIIlIlIlllIlIIIllllIlIIIlIIIII = "qPMsxAZenolAkYZWPxJoomGEJcpvdzaHydiwNFCPjqWSGAymjAhYqoIpMunggYdklCrbQDXrixmgPwF"
b16874994896344414163 = 102
V165 = "UasdQMqXfHOOvDghxbIkbQWvAdhbuVHLlQmhgdPpBVBwaQBMZgSXMjJWWMDzXkrUJNhRFhuSghcXxwr"
aAaAaAAAaAaAaAaaAaAAaaAAAAAAAaaAaAaaAAAaaaaAaAaaAaaaAAAAAAaAAaaAaaAaAaAAaAaaaaaAaAaAaAaAaAaAAAaAAAAaaaaaaaaaAaAaAAaAAAAAaAaaAAaaaAaaaaaaAAaAAaaAAAAAAAAAaaAAaAAAAaaAAAA = 616
DJOecsmVyPeYQEptHyIqUyjspPJwfxBFHXGEAvhpkUvtOAFLIfDttcmoiRYEiEeEqcUBvSgDFvaWLwO169 = 204
U171 = "wNkTTGALBokmStVXBguZPRXwCTQYRdjArDtbIDRxERvMtmYzcYnylmJBprnwXEONVFiVbnlxFFgORai"
IIlllIlIlIIlIlllllIIlllIIllllIlIlIlIlIIIIIIlIIlIIIlIIIIIIIlIIIIIlIllIlIlIIllIlllIIIIIIIIIIllllIIIlIIIlllIIIlIIIllIIlIlIlIIlllIlIllIIllIIllllIllIIlllIlIIIlllIlIIIIlIllllIIIlI = "tBmlCzPFisXMLXeEGfZwDdELWlystwzDHbDklKMrTaFjMjKmxTaRsskrjNLOuBNzgDtzGbezmfHWtyp"
llIllIIIIlIIIIlIllllIIlIIIIlIIIIllIIlllIlIIIlllIlIIIIIIIlIlIIIlIIlIIlllIlllIIlllIIIllllIlIlIIIlIIllIlIlIlIIlllIIlllIIIllIllllIIlIIllllIlIIIIIIllIllllllIIllIIllllIIlIIllIIlllIl = "USGmhwKzfLrtrXqhRwybrLsSYkHkKhKWPnudAWvPjyghIlzNBuBVcwAPqCiEUfGwsjxGjXqzXNZjmZL"
z177 = "TxVdNCiIIYbtwZLEBEzkTTsBWGyKZNfZWCxbeczexGrSqxljoHyOYUVzeWWoPFFYplDbCbXxFHAOtxN"
P179 = 522
llIIlIlIlllIlIlIIllIllIlIlIIIlllIIIIlllIlllllIllIIIlIlIlIlllIlIIlIIIlIllllIIlIIIllIlllllllIIIlIllIlllIIllIlIlIIllIIIlIlIIllIlIIlIlIlIIlllIlIIlllIIIIllIIIllIIlIllIlIllIIIllIIIllIIllI = 570
aaAaaAAAaAAaAaaaAaAaaaaAaAAAAaaAaAaAAaaaaAAAaaaAAaAAAAAAAAAAaAaAAAaAAAaaaaAAAAAaAAaAAAAAaaaAAaAAAaaaaaaaAAAaAaAaAAaAAAaaaaaAAAAaAAAaaaAaaAaAaAaAAAAaaAAaAaaaaAAaaAaaaaAAaaaAaAaAAAaaaaa = "eSAytDXvIiZSLdGGmCAHSevPUqhSfGXWpGpSezYUqrLrXeDBmQXIyqUuidwkcLDsxJjTKUltFPShDBm"